name: Build docs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Install dependencies
      run: |
        sudo pip3 install --system sphinx
    - uses: actions/checkout@v1
    - name: Set up DFHack
      run: |
        git clone git://github.com/dfhack/dfhack $HOME/dfhack --depth 1 --branch develop
        git -C $HOME/dfhack submodule update --init --depth 1 --remote plugins/stonesense library/xml
        rmdir $HOME/dfhack/scripts
        ln -sv $(pwd) $HOME/dfhack/scripts
    - name: Build docs
      run: |
        sphinx-build -qW -j3 $HOME/dfhack $HOME/dfhack/docs/html
    - name: Check for missing docs
      run: python3 $HOME/dfhack/travis/script-docs.py .
    - uses: actions/upload-artifact@master
      with:
        name: docs
        path: $HOME/dfhack/docs/html
